name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup
      id: setup
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: setup
        setup-command: ''
        command: pip install -r setup.txt
        input: ''
        expected-output: ''
        comparison-method: contains
        timeout: 1
        max-score: 0
    - name: result
      id: result
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: result
        setup-command: ''
        command: python result.py
        input: ''
        expected-output: '138'
        comparison-method: contains
        timeout: 1
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SETUP_RESULTS: "${{steps.setup.outputs.result}}"
        RESULT_RESULTS: "${{steps.result.outputs.result}}"
      with:
        runners: setup,result
